### ISSUE TITLE
Multiple Agents support

### ISSUE THREAD

**Issue by seifmostafa73** [hughperkins/peaceful-pie#2]
are there any plans to add multiple agents' support?

**Comment by hughperkins** [comment]
PeacefulPie is an unopinionated RPC layer. You can basically make any method calls you like from Python to Unity. It's a much lower level than agents, and RL, etc, so it doesn't have any opinions about agents, or how many agents, or whether you have any agents at all. So, you can totally use peaceful pie to train multiple agents. This is already possible.

What makes you feel that PeacefulPie will not work with multiple agents?

**Comment by seifmostafa73** [comment]
I'm concerned with how to handle multiple observations (specially stacked ones) for multiple agents .
 I'm still experimenting with some single agent environment and will try to add stacked the move to multiple agents so hope all goes smoothly.

**Comment by hughperkins** [comment]
Ok. There's an example in the examples/DungeonEscape folder, where we collect observations from multiple agents, and send them to python, https://github.com/hughperkins/peaceful-pie/blob/fb8b0bada72102d32c9247fbf3074573c48704e5/examples/DungeonEscape/Assets/DungeonEscape/Scripts/DungeonEscapeEnvController.cs#L271-L289   Now on the python side, I'm simply concatenating the observations from all agents, and feeding them to a single AI, https://github.com/hughperkins/peaceful-pie/blob/fb8b0bada72102d32c9247fbf3074573c48704e5/examples/DungeonEscape/python/my_unity_env.py#L60-L66 , which outputs three actions, https://github.com/hughperkins/peaceful-pie/blob/fb8b0bada72102d32c9247fbf3074573c48704e5/examples/DungeonEscape/python/my_unity_env.py#L33-L34  . However, you could freely modify the python side to treat each agent separately.

PeacefulPie doesn't express an opinion over how you handle different agents: as a single unit, like a chess player controls their pieces; or as individual agents, with no shared thought, or perception. It's all entirely up to you :)

**Comment by seifmostafa73** [comment]
That's extremely helpful , really appreciate the guidance
