### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by NDNM1408** [hughperkins/peaceful-pie#3]
I follow the same instruction from the tutorial but cannot connect to Unity, It's just output "requests.exceptions.ConnectionError => ignoring, retrying". Can anyone help me to resolve this?

**Comment by hughperkins** [comment]
Not much to go on in your question. Maybe provide screenshots depicting the state of your unity application, the code you are running, etc

**Comment by NDNM1408** [comment]
This is my python code, script for sphere and my setting in Unity, it just the same like you in your tutorial
![image](https://github.com/hughperkins/peaceful-pie/assets/98695231/f645a342-7243-44b2-8082-194118325b62)
![image](https://github.com/hughperkins/peaceful-pie/assets/98695231/61c3d128-9fc6-4e1a-b0fd-ad3190c4824e)
![image](https://github.com/hughperkins/peaceful-pie/assets/98695231/bc18c1c0-e777-4f17-9942-562efd892575)
And then when I run the python code it just meet ConnectionError
![image](https://github.com/hughperkins/peaceful-pie/assets/98695231/3c823c48-de2d-4b54-966d-b7a49d3f59ac)

**Comment by hughperkins** [comment]
Please include a screenshot showing your unity viewer is running

**Comment by NDNM1408** [comment]
![image](https://github.com/hughperkins/peaceful-pie/assets/98695231/e6bd8c05-8e20-448f-bd49-9dddba94ab1c)
Here is it

**Comment by hughperkins** [comment]
But it's not running. You have to press the 'play' button at the top. The button should look like this:

<img width="155" alt="Screenshot 2023-10-07 at 04 06 23" src="https://github.com/hughperkins/peaceful-pie/assets/123560/7ef99ad9-ee5a-4769-8a74-ea1c556afbe5">

**Comment by hughperkins** [comment]
I mean, I guess the viewer itself is running. But you need to run the application itself, inside the viewer.

**Comment by NDNM1408** [comment]
Oh I got it, thank you

**Comment by hughperkins** [comment]
Oh great! :)
