### ISSUE TITLE
async/await not supported

### ISSUE THREAD

**Issue by riichg5** [hughperkins/peaceful-pie#5]
unity server:

```
    [JsonRpcMethod]
    public async UniTask<AIMapStateData> GetMapState(int levelId, int hardLevel)
    {
        Debug.Log("GetMapState: -> " + levelId + " " + hardLevel);
        AIMapStateData res = await InternalGetMapState(levelId, hardLevel);
        Debug.Log("res: -> " + JsonMapper.ToJson(res));
        return res;
    }
```

python client:
```
        res = unity_comms.GetMapState(levelId=10, hardLevel=0)
        print("curent time:" , datetime.datetime.now(), 'res:', res)
```

python client print `{'Status': 0}`  immediately, but the server code is still executing.

**Comment by riichg5** [comment]
I resolved it by change the code of `PeacefulPie/NetManager.cs`.

**Comment by hughperkins** [comment]
Thanks. Don't suppose... could you post here the updated code please?

**Comment by riichg5** [comment]
NetManager.cs

---------------------------


using System;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using Cysharp.Threading.Tasks;
using AustinHarris.JsonRpc;
using UnityEngine;

class NetworkEvent
{
    // contains request from client, space for reply from server,
    // and a thread signaling thing so client can wait for reply
    // we'll keep everything as json strings here, and do the conversion
    // in the main thread
    public string clientRequest;
    public Task<string>? serverReply;
    public AutoResetEvent serverReplied = new AutoResetEvent(false);
    public NetworkEvent(string clientRequest)
    {
        this.clientRequest = clientRequest;
    }
}



public class NetManager : MonoBehaviour
{
    [Tooltip("Network port to listen on.")]
    public int ListenPort = 9000;
    [Tooltip("Network address to listen on. If not sure, put 'localhost'")]
    public string ListenAddress = "localhost";
    [Tooltip("Optional filepath to write logs to.")]
    public string? LogFilepath;
    [Tooltip("milliseconds to sleep after writing to logfile. Helps prevent runaway logs")]
    public int SleepAfterLogLineMilliseconds = 100;
    [Tooltip("Ensure the application runs in background. If you set this to false, you might wonder why your python scripts appears to hang")]
    public bool AutoEnableRunInBackground = true;

    bool blockingListen = false;
    bool isDedicated;
    volatile bool isEnabled = true;

    HttpListener? listener;
    BlockingCollection<NetworkEvent> networkEvents = new BlockingCollection<NetworkEvent>();

    void MyDebug(string msg)
    {
        if (LogFilepath != null && LogFilepath != "")
        {
            string DateTime = System.DateTime.Now.ToString("yyyyMMdd HH:mm:ss.fff");
            using (StreamWriter sw = File.AppendText(LogFilepath))
            {
                sw.WriteLine($"{DateTime} {msg}");
            }
            Thread.Sleep(SleepAfterLogLineMilliseconds);
        }
    }

    class RpcService : JsonRpcService
    {
        // this is only for turning blocking on/off
        NetManager netManager;

        public RpcService(NetManager netManager)
        {
            this.netManager = netManager;
        }

        [JsonRpcMethod]
        void shutdownUnity()
        {
            // This is intended for dedicatd servers that are spawned by UnityComms
            Debug.Log("received shutdownUnity()");
            Application.Quit();
            Debug.Log("After application.quit()");
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
            Debug.Log("after setting isPlaying to false");
#endif
            System.Diagnostics.Process.GetCurrentProcess().Kill();
            Debug.Log("after get current process . kill. hopefully we never get here :)");
        }

        [JsonRpcMethod]
        private void setBlockingListen(bool blocking)
        {
            // if blocking is true, then we listen for requests from python
            // using a blocking listen. This will run faster than non-blocking,
            // but if the python stops sending, then the editor will freeze, and the only
            // solution (other than restarting a python sender), is to Force Quit the Unity
            // Editor.
            this.netManager.SetBlocking(blocking);
        }
    }

    RpcService? rpcService;

    private void Awake()
    {
        rpcService = new RpcService(this);
        if (AutoEnableRunInBackground)
        {
            Application.runInBackground = true;
            Debug.Log("Enabled Application.runInBackground");
        }
        else
        {
            Debug.Log("Warning: NOT enabling Application.runInBackground. This means you will need to switch Unity to foreground for things to run.");
        }
    }

    public void SetBlocking(bool blocking)
    {
        Debug.Log($"Setting blocking network listen to {blocking}");
        this.blockingListen = blocking;
    }

    public bool IsDedicated()
    {
        return Screen.currentResolution.refreshRate == 0;
    }

    public void OnEnable()
    {
        isEnabled = true;
        isDedicated = IsDedicated();

        string[] args = System.Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length; i++)
        {
            if (args[i] == "--port")
            {
                ListenPort = int.Parse(args[i + 1]);
                Debug.Log($"Using port {ListenPort}");
            }
            else if (args[i] == "--help")
            {
                Debug.Log("Specify port with '--port [port number]'");
                Application.Quit();
                return;
            }
        }

        listener = new HttpListener();
        listener.Prefixes.Add($"http://{ListenAddress}:{ListenPort}/");

        listener.Start();
        // Task.Run(listenLoop);
        listenLoop();
        MyDebug($"Started listener, on address {ListenAddress} port {ListenPort}");
    }

    public void OnDisable()
    {
        isEnabled = false;
        Debug.Log("shutting down listener");
        if (listener is null)
        {
            return;
        }
        listener.Stop();
        listener.Abort();
        listener.Close();
    }

    void FixedUpdate()
    {
        int numIts = 0;
        // while (
        //  (networkEvents.Count > 0 && numIts == 0)
        //  || (blockingListen && numIts < 10)
        //  || (isDedicated && numIts == 0)
        // ) {
        if (networkEvents.Count > 0 || blockingListen || isDedicated)
        {
            NetworkEvent networkEvent = networkEvents.Take();
            networkEvent.serverReply = JsonRpcProcessor.Process(Handler.DefaultSessionId(), networkEvent.clientRequest, null);
            networkEvent.serverReplied.Set();
            numIts += 1;
        }
    }

    async Task handleRequest(HttpListenerContext context)
    {
        HttpListenerRequest req = context.Request;

        string bodyText;
        using (var reader = new StreamReader(req.InputStream, req.ContentEncoding))
        {
            bodyText = await reader.ReadToEndAsync();
        }

        NetworkEvent networkEvent = new NetworkEvent(bodyText);
        networkEvents.Add(networkEvent);
        // networkEvent.serverReply = JsonRpcProcessor.Process(networkEvent.clientRequest, context, null);
        networkEvent.serverReply = JsonRpcProcessor.Process(Handler.DefaultSessionId(), networkEvent.clientRequest, context, null);
        // networkEvent.serverReplied.Set();

        // 等待异步操作完成
        string? res = await networkEvent.serverReply;

        using HttpListenerResponse resp = context.Response;
        resp.Headers.Set("Content-Type", "application/json");

        Debug.Log("http response:" + res);
        byte[] buffer = Encoding.UTF8.GetBytes(res);
        resp.ContentLength64 = buffer.Length;

        using Stream ros = resp.OutputStream;
        await ros.WriteAsync(buffer, 0, buffer.Length);
    }

    public async Task listenOnceAsync()
    {
        if (listener is null)
        {
            return;
        }
        HttpListenerContext context = await listener.GetContextAsync();
        await handleRequest(context);
    }

    public async void listenLoop()
    {
        if (LogFilepath != null && LogFilepath != "")
        {
            File.OpenWrite(LogFilepath).Close();
        }
        while (true)
        {
            try
            {
                await listenOnceAsync();
            }
            catch (ObjectDisposedException error)
            {
                MyDebug("objectdisposedexception, error:" + error.Message);
                MyDebug($"isEnabled {isEnabled}");
                if (isEnabled)
                {
                    MyDebug("Looks like we are supposed to be still active. Lets reopen...");
                    try
                    {
                        if (listener != null)
                        {
                            listener.Abort();
                        }
                    }
                    catch (Exception e)
                    {
                        MyDebug($"exception during attempted abort {e}");
                        MyDebug($"(Ignoring exception))");
                    }
                    try
                    {
                        listener = new HttpListener();
                        listener.Prefixes.Add($"http://{ListenAddress}:{ListenPort}/");

                        listener.Start();
                        MyDebug($"Restarted listener");
                    }
                    catch (Exception e)
                    {
                        MyDebug($"error when trying to restart listener {e}");
                        throw e;
                    }
                }
                else
                {
                    // shutdown
                    break;
                }
            }
            catch (System.Net.HttpListenerException e)
            {
                if (e.Message == "Listener closed")
                {
                    MyDebug("listener closed");
                    break;
                }
                MyDebug($"HttpListenerException caught in httplistener {e}");
            }
            catch (System.Threading.ThreadAbortException)
            {
                MyDebug("threadabortexception");
                break;
            }
            catch (Exception e)
            {
                MyDebug($"Exception caught in httplistener {e}");
            }
        }
        MyDebug("ListenLoop shut down.");
    }
}

**Comment by hughperkins** [comment]
Thanks!

On Fri, Apr 12, 2024, at 4:37 AM, Bo Li wrote:
> 
> 
> NetManager.cs
> 
> 
> 
> using System;
> using System.IO;
> using System.Net;
> using System.Text;
> using System.Threading;
> using System.Collections.Concurrent;
> using System.Threading.Tasks;
> using Cysharp.Threading.Tasks;
> using AustinHarris.JsonRpc;
> using UnityEngine;
> 
> 
> class NetworkEvent
> {
> // contains request from client, space for reply from server,
> // and a thread signaling thing so client can wait for reply
> // we'll keep everything as json strings here, and do the conversion
> // in the main thread
> public string clientRequest;
> public Task? serverReply;
> public AutoResetEvent serverReplied = new AutoResetEvent(false);
> public NetworkEvent(string clientRequest)
> {
> this.clientRequest = clientRequest;
> }
> }
> 
> 
> public class NetManager : MonoBehaviour
> {
> [Tooltip("Network port to listen on.")]
> public int ListenPort = 9000;
> [Tooltip("Network address to listen on. If not sure, put 'localhost'")]
> public string ListenAddress = "localhost";
> [Tooltip("Optional filepath to write logs to.")]
> public string? LogFilepath;
> [Tooltip("milliseconds to sleep after writing to logfile. Helps prevent runaway logs")]
> public int SleepAfterLogLineMilliseconds = 100;
> [Tooltip("Ensure the application runs in background. If you set this to false, you might wonder why your python scripts appears to hang")]
> public bool AutoEnableRunInBackground = true;
> 
> `bool blockingListen = false;
> bool isDedicated;
> volatile bool isEnabled = true;
> 
> HttpListener? listener;
> BlockingCollection<NetworkEvent> networkEvents = new BlockingCollection<NetworkEvent>();
> 
> void MyDebug(string msg)
> {
>     if (LogFilepath != null && LogFilepath != "")
>     {
>         string DateTime = System.DateTime.Now.ToString("yyyyMMdd HH:mm:ss.fff");
>         using (StreamWriter sw = File.AppendText(LogFilepath))
>         {
>             sw.WriteLine($"{DateTime} {msg}");
>         }
>         Thread.Sleep(SleepAfterLogLineMilliseconds);
>     }
> }
> 
> class RpcService : JsonRpcService
> {
>     // this is only for turning blocking on/off
>     NetManager netManager;
> 
>     public RpcService(NetManager netManager)
>     {
>         this.netManager = netManager;
>     }
> 
>     [JsonRpcMethod]
>     void shutdownUnity()
>     {
>         // This is intended for dedicatd servers that are spawned by UnityComms
>         Debug.Log("received shutdownUnity()");
>         Application.Quit();
>         Debug.Log("After application.quit()");
`
> 
> #if UNITY_EDITOR
> UnityEditor.EditorApplication.isPlaying = false;
> Debug.Log("after setting isPlaying to false");
> #endif
> System.Diagnostics.Process.GetCurrentProcess().Kill();
> Debug.Log("after get current process . kill. hopefully we never get here :)");
> }
> 
> `    [JsonRpcMethod]
>     private void setBlockingListen(bool blocking)
>     {
>         // if blocking is true, then we listen for requests from python
>         // using a blocking listen. This will run faster than non-blocking,
>         // but if the python stops sending, then the editor will freeze, and the only
>         // solution (other than restarting a python sender), is to Force Quit the Unity
>         // Editor.
>         this.netManager.SetBlocking(blocking);
>     }
> }
> 
> RpcService? rpcService;
> 
> private void Awake()
> {
>     rpcService = new RpcService(this);
>     if (AutoEnableRunInBackground)
>     {
>         Application.runInBackground = true;
>         Debug.Log("Enabled Application.runInBackground");
>     }
>     else
>     {
>         Debug.Log("Warning: NOT enabling Application.runInBackground. This means you will need to switch Unity to foreground for things to run.");
>     }
> }
> 
> public void SetBlocking(bool blocking)
> {
>     Debug.Log($"Setting blocking network listen to {blocking}");
>     this.blockingListen = blocking;
> }
> 
> public bool IsDedicated()
> {
>     return Screen.currentResolution.refreshRate == 0;
> }
> 
> public void OnEnable()
> {
>     isEnabled = true;
>     isDedicated = IsDedicated();
> 
>     string[] args = System.Environment.GetCommandLineArgs();
>     for (int i = 0; i < args.Length; i++)
>     {
>         if (args[i] == "--port")
>         {
>             ListenPort = int.Parse(args[i + 1]);
>             Debug.Log($"Using port {ListenPort}");
>         }
>         else if (args[i] == "--help")
>         {
>             Debug.Log("Specify port with '--port [port number]'");
>             Application.Quit();
>             return;
>         }
>     }
> 
>     listener = new HttpListener();
>     listener.Prefixes.Add($"http://{ListenAddress}:{ListenPort}/");
> 
>     listener.Start();
>     // Task.Run(listenLoop);
>     listenLoop();
>     MyDebug($"Started listener, on address {ListenAddress} port {ListenPort}");
> }
> 
> public void OnDisable()
> {
>     isEnabled = false;
>     Debug.Log("shutting down listener");
>     if (listener is null)
>     {
>         return;
>     }
>     listener.Stop();
>     listener.Abort();
>     listener.Close();
> }
> 
> void FixedUpdate()
> {
>     int numIts = 0;
>     // while (
>     //  (networkEvents.Count > 0 && numIts == 0)
>     //  || (blockingListen && numIts < 10)
>     //  || (isDedicated && numIts == 0)
>     // ) {
>     if (networkEvents.Count > 0 || blockingListen || isDedicated)
>     {
>         NetworkEvent networkEvent = networkEvents.Take();
>         networkEvent.serverReply = JsonRpcProcessor.Process(Handler.DefaultSessionId(), networkEvent.clientRequest, null);
>         networkEvent.serverReplied.Set();
>         numIts += 1;
>     }
> }
> 
> async Task handleRequest(HttpListenerContext context)
> {
>     HttpListenerRequest req = context.Request;
> 
>     string bodyText;
>     using (var reader = new StreamReader(req.InputStream, req.ContentEncoding))
>     {
>         bodyText = await reader.ReadToEndAsync();
>     }
> 
>     NetworkEvent networkEvent = new NetworkEvent(bodyText);
>     networkEvents.Add(networkEvent);
>     // networkEvent.serverReply = JsonRpcProcessor.Process(networkEvent.clientRequest, context, null);
>     networkEvent.serverReply = JsonRpcProcessor.Process(Handler.DefaultSessionId(), networkEvent.clientRequest, context, null);
>     // networkEvent.serverReplied.Set();
> 
>     // 等待异步操作完成
>     string? res = await networkEvent.serverReply;
> 
>     using HttpListenerResponse resp = context.Response;
>     resp.Headers.Set("Content-Type", "application/json");
> 
>     Debug.Log("http response:" + res);
>     byte[] buffer = Encoding.UTF8.GetBytes(res);
>     resp.ContentLength64 = buffer.Length;
> 
>     using Stream ros = resp.OutputStream;
>     await ros.WriteAsync(buffer, 0, buffer.Length);
> }
> 
> public async Task listenOnceAsync()
> {
>     if (listener is null)
>     {
>         return;
>     }
>     HttpListenerContext context = await listener.GetContextAsync();
>     await handleRequest(context);
> }
> 
> public async void listenLoop()
> {
>     if (LogFilepath != null && LogFilepath != "")
>     {
>         File.OpenWrite(LogFilepath).Close();
>     }
>     while (true)
>     {
>         try
>         {
>             await listenOnceAsync();
>         }
>         catch (ObjectDisposedException error)
>         {
>             MyDebug("objectdisposedexception, error:" + error.Message);
>             MyDebug($"isEnabled {isEnabled}");
>             if (isEnabled)
>             {
>                 MyDebug("Looks like we are supposed to be still active. Lets reopen...");
>                 try
>                 {
>                     if (listener != null)
>                     {
>                         listener.Abort();
>                     }
>                 }
>                 catch (Exception e)
>                 {
>                     MyDebug($"exception during attempted abort {e}");
>                     MyDebug($"(Ignoring exception))");
>                 }
>                 try
>                 {
>                     listener = new HttpListener();
>                     listener.Prefixes.Add($"http://{ListenAddress}:{ListenPort}/");
> 
>                     listener.Start();
>                     MyDebug($"Restarted listener");
>                 }
>                 catch (Exception e)
>                 {
>                     MyDebug($"error when trying to restart listener {e}");
>                     throw e;
>                 }
>             }
>             else
>             {
>                 // shutdown
>                 break;
>             }
>         }
>         catch (System.Net.HttpListenerException e)
>         {
>             if (e.Message == "Listener closed")
>             {
>                 MyDebug("listener closed");
>                 break;
>             }
>             MyDebug($"HttpListenerException caught in httplistener {e}");
>         }
>         catch (System.Threading.ThreadAbortException)
>         {
>             MyDebug("threadabortexception");
>             break;
>         }
>         catch (Exception e)
>         {
>             MyDebug($"Exception caught in httplistener {e}");
>         }
>     }
>     MyDebug("ListenLoop shut down.");
> }
`
