### ISSUE TITLE
Any performance disadvantages compared to ml-agents

### ISSUE THREAD

**Issue by RishiMalhotra920** [hughperkins/peaceful-pie#6]
Hey, I definitely prefer how much freedom this package provides me with to implement my RL algorithms and that it allows me to use gym-like wrapper classes for implementation.

I was curious about the performance advantages/disadvantages of peaceful-pie compared to unity ml-agents. Has unity ml-agents been optimized for this work in some way that peaceful-pie hasn't?

Let me know!

**Comment by hughperkins** [comment]
I found that my own implementation of Dungeon Escape learned faster and better than mlagents, https://github.com/hughperkins/peaceful-pie/tree/main/examples/DungeonEscape  I should write that up and/or create a video. But in the meantime, you could try yourself, and see how the two approaches compare performance-wise?
